version: "3"
services:
  server:
    container_name: server
    restart: always
    build: .
    volumes:
      - .:/usr/server
    ports:
      - 3000:3000
    networks:
      - secretsunsealed
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - su_db:/data/db
    ports:
      - 27017:27017
    networks:
      - secretsunsealed
volumes:
  ? su_db
networks:
  ? secretsunsealed
